title: Kelby Sandvick # your name (or website title) here
logo: "/images/myAvatarLarge.jpg?raw=true" # avatar drawing
#logo: "/images/workPhoto.jpg?raw=true" # work photo
description: > # your text below (remove <br> elements if you don't need line breaks)
  Bachelor of Science
  <br>
  Major in Computer Science, <br>
  Minor in Interactive Art and Computing <br>
  Graduating June, 2021
  <br> <br>
  <a href="https://www.linkedin.com/in/kelbysandvick/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
